/* eslint-disable jsx-a11y/alt-text */
/* eslint-disable @next/next/no-img-element */

import Head from 'next/head';

import {FC, useState} from 'react';
import CardList from '../components/CardList';
import Search from '../components/Search';
import {IDat, IData} from '../share/interface';

const Home: FC<IData> = ({data}) => {
  const Action = data.filter(
    data => data.genres[0] === 'Action' && data.rating.average > 7.5,
  );

  const Drama = data.filter(
    data => data.genres[0] === 'Drama' && data.rating.average > 8.5,
  );

  const Comedy = data.filter(
    data => data.genres[0] === 'Comedy' && data.rating.average > 8,
  );
  const [search, setSearch] = useState('');

  const Filter = data.filter(val => {
    if (search == '') {
      return '';
    } else if (val.name.toLowerCase().includes(search.toLowerCase())) {
      return val.name;
    }
  });

  return (
    <>
      <Head>
        <title>TvMaze API</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/cine.ico" />
      </Head>

      <Search setSearch={setSearch}></Search>

      <div className="bg-gray">
        <div className="bg-back flex justify-center p-2 m-2">
          <CardList moviesArray={Filter}></CardList>
        </div>

        <div className="text-center pb-6 lg:px-4 bg-red-300">
          <p className="m-4 text-xl">Action</p>
          <CardList moviesArray={Action} />
        </div>
        <div className="text-center pb-6 lg:px-4 bg-blue-400">
          <p className="m-4 text-xl">Drama</p>
          <CardList moviesArray={Drama} />
        </div>
        <div className="text-center pb-6 px-4 bg-yellow-400">
          <p className="m-4 text-xl">Comedy</p>
          <CardList moviesArray={Comedy} />
        </div>
      </div>
    </>
  );
};

export const getStaticProps = async () => {
  try {
    const res = await fetch(` https://api.tvmaze.com/shows`);
    const data: IDat[] = await res.json();

    return {
      props: {
        data,
      },
    };
  } catch (e) {
    console.log(e);
  }
};

export default Home;
