/* eslint-disable jsx-a11y/alt-text */
/* eslint-disable @next/next/no-img-element */

import Head from 'next/head';
import Link from 'next/link';
import {FC, useState} from 'react';
import CardList from '../components/CardList';
import Search from '../components/Search';
import {IDat, IData} from '../share/interface';

const Home: FC<IData> = ({data}) => {
  console.log(data);

  const Action = data.filter(
    data => data.genres[0] === 'Action' && data.rating.average > 7.5,
  );

  const Drama = data.filter(
    data => data.genres[0] === 'Drama' && data.rating.average > 8.5,
  );

  const Comedy = data.filter(
    data => data.genres[0] === 'Comedy' && data.rating.average > 8,
  );
  /* const [search, setSearch] = useState(''); */

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* {data.map(({id, name, genres, image, rating}) => (
        <div key={id}></div>
      ))} */}
      {/*  <Search setSearch={setSearch}></Search>
      {data
        .filter((val: any) => {
          if (search == '') {
            return val;
          } else if (val.name.toLowerCase().includes(search.toLowerCase())) {
            return val;
          }
        })
        .map(({name, id}) => (
          <div key={id}></div>
        ))} */}

      <div>
        Action
        <CardList moviesArray={Action} />
      </div>
      <div>
        Drama
        <CardList moviesArray={Drama} />
      </div>
      <div>
        Comedy
        <CardList moviesArray={Comedy} />
      </div>
    </>
  );
};

export const getStaticProps = async () => {
  try {
    const res = await fetch(` https://api.tvmaze.com/shows`);
    const data: IDat[] = await res.json();

    return {
      props: {
        data,
      },
    };
  } catch (e) {
    console.log(e);
  }
};

export default Home;
