/* eslint-disable jsx-a11y/alt-text */
/* eslint-disable @next/next/no-img-element */
import Head from 'next/head';
import {FC, useState} from 'react';
import CardList from '../components/CardList';

import Search from '../components/Search';
import {IData} from '../share/interface';

const Home: FC<IData> = ({data}) => {
  console.log(data);

  const [search, setSearch] = useState('');
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <Search setSearch={setSearch}></Search>
      </div>
      {/* <div>Action</div> */}

      {data
        .filter((val: any) => {
          if (search == '') {
            return val;
          } else if (val.name.toLowerCase().includes(search.toLowerCase())) {
            return val;
          }
        })
        .map(x => (
          <div key={x.id}>
            <div className="flex">
              <CardList x={x} genres={'Action'} />
            </div>
            <br />
            <br />
            <br />
            <CardList x={x} genres={'Drama'} />

            {/* <CardList x={x} genres={'Drama'} /> */}

            {/* <p>
                  {id} - {name}
                  <img src={image.medium} />
                </p> */}
            {/* <div className="">
                  {id <= 50 ? (
                    genres['0'] === 'Action' ? (
                      <div className="bg-gray-600">
                        <p className="">
                          {id} - {name}
                          <img src={image.medium} />
                        </p>
                      </div>
                    ) : (
                      ''
                    )
                  ) : (
                    ''
                  )}
                </div>
              
                <div className="">
                  {id <= 50 ? (
                    genres[0] === 'Drama' ? (
                      <div className="bg-red-900 ">
                        <p className="">
                          {id} - {name}
                          <img src={image.medium} />
                        </p>
                      </div>
                    ) : (
                      ''
                    )
                  ) : (
                    ''
                  )}
                </div> */}
          </div>
        ))}
    </>
  );
};

export const getStaticProps = async () => {
  try {
    const res = await fetch(` https://api.tvmaze.com/shows`);
    const data = await res.json();

    return {
      props: {
        data,
      },
    };
  } catch (e) {
    console.log(e);
  }
};

export default Home;
